### ISSUE TITLE
Same etag everytime, empty dict

### ISSUE THREAD

**Issue by tialm** [jozo/django-rest-framework-condition#11]
I am trying to use this library but I am having a problem with ETags. The Etag I get is always the same, upon further inspection I have noticed that the request dict is always empty. Any suggestion? Here is my code:

```
def my_etag(request, *args, **kwargs):
    return hashlib.md5(':'.join(request.GET.dict().values()).encode('utf-8')).hexdigest()


class DeviceMachines(generics.ListAPIView):
    queryset = Device.objects.all()
    serializer_class = DeviceMachinesSerializer

    def get_queryset(self):
        queryset = super(DeviceMachines, self).get_queryset()
        device = queryset.filter(id=self.kwargs['device_id'])
        store = Store.objects.filter(name=device[0].store)
        machines = Machine.objects.filter(store__in=store)
        return machines

    @etag(my_etag)
    def list(self, request, *args, **kwargs):
        queryset=super(DeviceMachines, self).list(request, *args, **kwargs)
        queryset.data = {
            'machines': queryset.data
        }
        return Response(queryset.data)
```

Thank you!

**Comment by jozo** [comment]
Function `my_etag` is just for the example. You need to write your own etag function based on your needs. You can find more information here: https://docs.djangoproject.com/en/dev/topics/conditional-view-processing/

**Comment by tialm** [comment]
Thank you @jozo , I am trying to achieve that and already went through the link you suggested. My problem is when I return a Response object and try to get the data in the etag func with request.GET it always return an empty dict... then no matter what my funcion is the etag will always be the same. Any idea why the request.GET is not working? My view is woring fine if I don't use the etag

**Comment by jozo** [comment]
Of course the etag will be same if requests.GET is always empty. That's correct behaviour. Etag should be same if you provide same input data.

You have to create your own etag function (which probably won't use requests.GET). The correct way how to do it is to think about what will define your objects. Maybe you can use some data from your models which will be used to generate etag?

**Comment by tialm** [comment]
But my question is, why is the request always empty? It's not supposed to... My queryset.data is actually not empty and I get the results I want on my website. But when I try to parse the request on the etag function it's empty.
Anyway, I'll try your suggestion, I just wanted to know why I can't access the data inside the etag func

**Comment by jozo** [comment]
It's empty because you didn't provide HTTP GET parameters. Read docs here: https://docs.djangoproject.com/en/dev/ref/request-response/#django.http.HttpRequest.GET

Anyway, this discussion is not about this lib anymore => closing the issue.
