### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by YPCrumble** [jozo/django-rest-framework-condition#13]
Hi, first thanks for writing this package! I found it when researching some improvements I'm making to django-fancy-cache: https://github.com/peterbe/django-fancy-cache/issues/67

I'm looking to integrate etags into my rest framework site but can't use GPL-licensed software. Would you be willing to consider a different license, e.g., MIT?

**Comment by jozo** [comment]
Sure, why not. I've changed it. Here: https://github.com/jozo/django-rest-framework-condition/commit/2678a5220f4e5270c5136c314d4552c5fd3f5371
